### ISSUE TITLE
Hangs on boot with LayeredFS

### ISSUE THREAD

**Issue by ghost** [jakibaki/sys-ftpd#1]
Loading the system module with LayeredFS will cause the console to hang at boot on the "Nintendo Switch" logo screen.

**Comment by jakibaki** [comment]
Yeah that's a known issue that I unfortunately can't do much about until there's a way to load non-pkg2-sysmodules. :/

We need a certain amount of ram to run this and there apparently is only so much ram to share between sysmodules that it isn't enough for both layeredfs and this.

**Comment by jakibaki** [comment]
I fixed it! Was as I suspected ram-usage but I managed to reduce it far enough :)
