### ISSUE TITLE
Tinfoil crashing when trying to install with sys-ftpd intalled

### ISSUE THREAD

**Issue by Zedjones** [jakibaki/sys-ftpd#11]
With the latest version of ReiNX and Tinfoil, Tinfoil gets stuck on the "Installing 1/1" prompt after selecting a .nsp to install. Not sure if this is specifically related to sys-ftpd, but removing the .kip file on the latest commit seems to resolve the issue. The issue still persists even if sys-ftpd is turned off (Minus + Plus + X). 

System Information:
XAW1007XXXXXX
System v4.1.0
ReiNX v1.2
Tinfoil commit f195e9c47b855a6341552ad0efd0dd7140835363
sys-ftpd commit 41fd7ee552d10f3f2c72310f70e0a0dcca858ea1

**Comment by jakibaki** [comment]
ReiNX is not 'officially' supported. Please try if the issue still persists with the hekate sdfiles.

(In any case this probably is caused by the missing pm.kip in reinx which can be just dragged over from the sdfiles afaik)
