### ISSUE TITLE
Move /ftpd to /modules/sysftpd/ftpd

### ISSUE THREAD

**Issue by fennectech** [jakibaki/sys-ftpd#16]
Can we move the ftpd folder inthe sdcard to /modules/sysftpd?

**Comment by jakibaki** [comment]
I'd rather let sys-ftpd be as "cfw independent" as possible.

That change would make sense in the sdfiles but nowhere else.

**Comment by fennectech** [comment]
How about something like /bootloader or /atmosphere.    Just check a few different places and let the user choose the directory location?
