### ISSUE TITLE
Dirty Authentication patch

### ISSUE THREAD

**Issue by fennectech** [jakibaki/sys-ftpd#17]
I plan to mantain the dirty authentication patch here.   Can you keep this open until the feature is implimented properly?

**Comment by fennectech** [comment]
https://gist.github.com/fennectech/177bd7cb0a8b24c7085018b7be2fd139 
Works as of monday november ninth 2018

**Comment by ghost** [comment]
How does it work?

**Comment by fennectech** [comment]
You compile it with your username and password then use the resulting kip.  Has it broken?

**Comment by jakibaki** [comment]
Thanks to @KranKRival this is now configurable out of the box through an ini-file! :)

**Comment by fennectech** [comment]
@KranKRival    ON THIS DAY YOU ARE KING.
