### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by blawar** [jakibaki/sys-ftpd#22]
You cannot convert the entire code base to GPL, because you do not own a copyright on that, only on the changes you made to port it to the switch.

However it seems you slapped a generic GPL license on the entire code base which is illegal.

The easiest solve here is to just re-license the entire project back to the original author's license.

**Comment by jakibaki** [comment]
Original license was the unlicense which allows my behaviour...

```
A license with no conditions whatsoever which dedicates works to the public domain. Unlicensed works, modifications, and larger works may be distributed under different terms and without source code.
```

**Comment by blawar** [comment]
The issue is not that you used the code, the issue is that you copyrighted code that is not yours which is stealing.  You need to clarify which parts are copyrighted by you, and which parts are not.

**Comment by jakibaki** [comment]
Do I? It pretty explicitly states that I may redistribute it under different terms.

If you want to fork something under the terms of the original license, just fork the original project.

**Comment by blawar** [comment]
The license literally says it is public domain, you cannot place a copyright on public domain works.  This is the equivilent of you copyrighting Beethoven.  You simply cannot do it, it is theft and illegal.

**Comment by jakibaki** [comment]
Could you please provide a source for that?

It pretty explicitly states that it also works with closed source software which obviously can be under different licenses. Why would not explicitly marking where the code is used be ok in closed source software but not in open one?

**Comment by blawar** [comment]
https://fairuse.stanford.edu/overview/public-domain/welcome/

"The term “public domain” refers to creative materials that are not protected by intellectual property laws such as copyright, trademark, or patent laws."

You cannot copyright it.

**Comment by jakibaki** [comment]
I definitely know that the unlicense is compatible with gpl so that I can absolutely use code which is under this license in my project. https://www.gnu.org/licenses/license-list.de.html

If you have any source for if/how parts of the project which come from unlicensed code come are to be marked I'll happily oblige.

**Comment by blawar** [comment]
Mixing copyright licenses is complex, thats why I said the easiest thing to do is just convert the entire project to the original author's license.

If you do want your specific code to be GPL'd, the easiest thing to do is try to keep all of your code into their own files, and put the copyright notice on the top of those files, and then put the original author's license at the top of all of his files, and then amend your LICENSE file to show that the project falls under a variety of licenses.

that ftp.c file is pretty monolithic, you could also solve this up by breaking it up into smaller files, and then putting your GPL license at the top of the files that contain only your code / modifications.

**Comment by jakibaki** [comment]
I guess I can unlicense the `ftp.c` file if it makes you happy.

**Comment by blawar** [comment]
That would be a good solve.  Thank you for your contributions, I respect the work you do.

**Comment by nnsee** [comment]
Sorry @blawar, you're wrong.

The Unlicense is not a copyleft license. Whoever uses Unlicense-licensed code can do whatever they please with it, **including relicensing it under different terms**. In fact, [that was a big reason for why the author of Unlicense came up with it in the first place](https://ar.to/2010/01/set-your-code-free). @jakibaki  may license the entire project however he wants.

**Comment by jarulo** [comment]
Slapping GPL license on the public domain code is futile. Since anyone can just take the public domain code and do as they please.

Otherwise people would see the sys-ftpd GPL licensed code in some other project, and think it is a violation of the GPL license, while in actuality the public domain code is free to be used as people please

**Comment by nnsee** [comment]
Sure, with no modifications to the piece of code in question, it is still effectively public domain and a GPL license on it is not enforceable. Still doesn't mean that the author cannot do so if he wishes.

**Comment by blawar** [comment]
@neonsea you cited a blog about an author who decided to "unlicense" his code.   Noone is saying jakibaki cannot distribute public domain code, simply that slapping a copyright notice on code he does not own a copyright to is not legal.

That would be like me trademarking a name someone else is using.

**Comment by blawar** [comment]
@jarulo I agree it is futile, since it is effectively unenforceable since jakibaki does not own a copyright to it.  By slapping a GPL license on it, he is lying and claiming ownership over code he does not own, akin to stolen valor.  On top of that, it tells people that they cannot copy code, that legally they are allowed to copy which is also wrong.

**Comment by nnsee** [comment]
Unfortunately, that's just how public domain works. He can GPL the entire project, including any works in PD (parts of code from PD distributed in a package). Similarly, as soon as he modifies that piece of code, he can copyright it.

https://fairuse.stanford.edu/overview/public-domain/trouble-spots/#public_domain_works_that_are_modified

**Comment by blawar** [comment]
@neonsea your link bolsters my point:  he is free to copyright his modifications, but not the entire work.  Copyright literally means you own it.  Jakibaki did not write that code, he cannot assert copyright over it.  If modifying a few lines of code woudl grant a copyright to the entire work, scires would have a copyright over Horizon.

**Comment by nnsee** [comment]
"A famous example used in many copyright classes is the artist who paints an elaborate hat and mustache on the Mona Lisa. Even though anyone is free to copy the image of the Mona Lisa, **the modified image**  (with mustache and hat) is protected under the artist’s copyright."

And of course Scires doesn't have copyright over Horizon, it's not even in public domain - I don't see how this is relevant?

**Comment by blawar** [comment]
@neonsea the act of adding the mustache and hat would be copyrightable (the modification).  however if you took a picture of it, and censored out he hat and mustache, they would not be able to assert a copyright claim because hey never had a copyright to the original work, only the modifications.

**Comment by blawar** [comment]
Noticed you are still illegally copyrighting public domain code.  Shame.

I also do not see the libnx license being distributed, or any other software projects you used, in violation of their licenses.
