### ISSUE TITLE
Turn on LED on all controlers when user connected

### ISSUE THREAD

**Issue by fennectech** [jakibaki/sys-ftpd#33]
Can we turn on the LEDs when the ftpd receves a connection 
Libnx has recently added support   here are the relevant commits

https://github.com/switchbrew/libnx/commit/46d5771312ee69e791130a927cede4bb3c7ec6e0
https://github.com/switchbrew/libnx/commit/bed9213f41758da3b107faf94e86c1011a79e16e
https://github.com/switchbrew/libnx/issues/240

**Comment by fennectech** [comment]
Another relevant commit 
https://github.com/switchbrew/libnx/commit/aad6b55793e4adfc498c1f7e1ae9ebcdf8f17a3a
https://github.com/switchbrew/libnx/pull/272/commits/7cc6411ad53a7c3040ff40e1d510342d47c9915b 
And another

**Comment by jakibaki** [comment]
PRs are very welcome for this :)
