### ISSUE TITLE
Ability to decide what port the service listens on

### ISSUE THREAD

**Issue by fennectech** [jakibaki/sys-ftpd#5]
I would like tobe able to have ftpd listen on port 21     This alolng with the other options should be specifiable by a config file.

**Comment by Zedjones** [comment]
Would an ini file work for this? I could probably whip something up. I'd also recommend looking into [inih](https://github.com/benhoyt/inih), I'm currently using it for ini parsing and it works really well.

**Comment by friedkeenan** [comment]
libconfig might be good for this, since it has devkitpro support

**Comment by fennectech** [comment]
THat would also allow adding the user/pass.  As those can just be passed to variables

**Comment by fennectech** [comment]
I have not managed to compile the service to listen on port 21 tho.   I can set it to but it doesn’t actually listen.

**Comment by KranKRival** [comment]
this issue have been delt with and i added full config support implaminattion 
user , password , anonymous , port 
latest commit is on my git hub with port configuration support aswell , until its get merged to main repo
this issue can be clossed now i gues xD!
