### ISSUE TITLE
Latest sys-ftpd build still struggling with bandwidth

### ISSUE THREAD

**Issue by cryptolute** [jakibaki/sys-ftpd#8]
Updated to v7 SD-files and eager to test FTP speeds as that is a big feature for me personally. I got 800k/s with the new setup, which is a slight improvement, but unfortunately not close to the point where it is a usable feature.

My desktop is connected via GBIT port to a r7500 v2, switch is connected to the 5ghz band and I even sat the switch 12 inches from the router to see if that would improve speed but it did not, 800k/s was consistent.

If you would like me to test specifics, please let me know and thank you.

**Comment by jakibaki** [comment]
Could you please try the build from here: https://jenkins.stayathomeserver.club/job/sys-ftpd/lastSuccessfulBuild/artifact/sys-ftpd.kip

That might solve your problem.

**Comment by cryptolute** [comment]
@jakibaki - I have tested that kip and actually got slower speeds, clocked in between 650-700k/s.  Sorry :(

**Comment by jakibaki** [comment]
:/ all I can say is works fine for me

**Comment by fennectech** [comment]
I get about 1.2 megabytes per second too.

**Comment by jakibaki** [comment]
[sys-ftpd.kip.zip](https://github.com/jakibaki/sys-ftpd/files/2298436/sys-ftpd.kip.zip)
Could you please try this experimental build?

My switch is broken right now so I can't test it myself.

**Comment by fennectech** [comment]
Hangs on boot.    volume slider comes up and buttons make noise but nothing else happens.

**Comment by jakibaki** [comment]
ok, thanks for checking ;/

**Comment by jakibaki** [comment]
[sys-ftpd.kip.zip](https://github.com/jakibaki/sys-ftpd/files/2319080/sys-ftpd.kip.zip)
Please try this build.  
This might actually help and I already confirmed that it doesn't break like the last one.

**Comment by cryptolute** [comment]
@jakibaki - This build is much better, clocks in at steady 2.4mb/s

Thank you for your continued support of this project.  Hopefully we can get tumger to intergrate this version in future sdfiles releases :) If you want me to continue testing builds, please keep this issue open so that I will receive notifications on the responses.

**Comment by jakibaki** [comment]
Ah, neat! :) Thanks for the help!

I pushed the changes and will finally close this issue now!

**Comment by fennectech** [comment]
Ill let him know.

**Comment by fennectech** [comment]
Already is in :D
